language: c
os:
  - linux
  - osx
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:smspillaz/cmake-2.8.12; sudo apt-get update -qq; sudo apt-get install -q -y cmake cmake-data libpng12-dev zlib1g-dev libjson0-dev libfontconfig1-dev libgtkmm-2.4-dev libpangomm-1.4-dev libgl1-mesa-dev libglu-dev libglew-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake libpng; fi
script:
  - mkdir cbuild
  - cd cbuild
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
